# -*- coding: utf-8 -*-
"""Gemini_Eczema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Avishkarm/EczemaDetection/blob/main/src/eczema_detection/Gemini_Eczema.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q -U google-generativeai
# %pip install python-dotenv

import google.generativeai as genai
from IPython.display import Markdown

"""Generate api key here: https://aistudio.google.com/app/apikey"""

import os
from dotenv import load_dotenv

# Add API key in .env file
# Example: GOOGLE_API_KEY=your-api-key

load_dotenv()

GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')  # Retrieve the API key from env file.

if GOOGLE_API_KEY is None:
    raise ValueError("API key not found. Please set it as an environment variable: GOOGLE_API_KEY")

genai.configure(api_key=GOOGLE_API_KEY)

print("API key configured successfully!")

# Pick image from dataset
sample_file = genai.upload_file(path=r"..\..\dataset\eczema\Eczema of Hands\eczema-hand-189.jpg",
                            display_name="Sample image")

file = genai.get_file(name=sample_file.name)
print(f"Retrieved file '{file.display_name}' as: {sample_file.uri}")

# Choose a Gemini model.
model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest")

# Create a prompt to detect bounding boxes.
prompt = "Return whether the provided image is skin or not and which part of the body it is "
response = model.generate_content([sample_file, prompt])

Markdown(response.text)

# Prompt to check if eczema
prompt = "Return whether the provided image is a case of eczema and explain how severe the case is and what remedies can be availed"
response = model.generate_content([sample_file, prompt])

Markdown(response.text)

# Add details of patient to prompt inspect how output changes

# Patient details in years, cm and kg
age = 30
gender = "Female"
height = 170
weight = 100

# Create a new prompt with patient details
detailed_prompt = f"Patient details: Age: {age}, Gender: {gender}, Height: {height} cm, Weight: {weight} kg. " \
                  f"Return whether the provided image is a case of eczema and explain how severe the case is and what remedies can be availed."

response = model.generate_content([sample_file, detailed_prompt])

Markdown(response.text)

# Add details of patient to prompt inspect how output changes

# Patient details in years, cm and kg
age = 12
gender = "Male"
height = 145
weight = 30

# Create a new prompt with patient details
detailed_prompt = f"Patient details: Age: {age}, Gender: {gender}, Height: {height} cm, Weight: {weight} kg. " \
                  f"Return whether the provided image is a case of eczema and explain how severe the case is and what remedies can be availed."

response = model.generate_content([sample_file, detailed_prompt])

Markdown(response.text)